artcl_collect_list:
  - /var/log/
  - /home/stack/.instack/install-undercloud.log
  - /home/stack/stackrc
  - /home/stack/overcloudrc
  - /home/stack/*.log
  - /home/stack/*.json
  - /home/stack/*.conf
  - /home/stack/*.yml
  - /home/stack/*.yaml
  - /home/stack/*.sh
  - /home/stack/deploy-overcloudrc
  - /home/stack/network-environment.yaml
  - /home/stack/local_tht
  - /usr/share/openstack-tripleo-heat-templates
artcl_gzip_only: true
